# Generated by Django 4.0.7 on 2022-08-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_massemail_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='mail_system',
            field=models.CharField(choices=[('Exchange', 'Exchange'), ('SendGrid', 'SendGrid')], default='EXCHANGE', max_length=100, verbose_name='Mail System'),
            preserve_default=False,
        ),
    ]
